[package]
name = "glover-patch"
version = "0.1.0"
authors = ["Lukas Krickl <lukas@krickl.dev>"]
edition="2021"

[[bin]]
name = "payload"
path = "src/main.rs"

[dependencies]
ultra-rs = { path = "../lib" }
linked_list_allocator = "0.9.1"
